[package]
name = "clean-deps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytesize = "1.3.0"
clap = { version = "4.4.11", features = ["derive"] }
colored = "2.1.0"
